name: Daily PuckTracker Update

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  update-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger secure update
        run: |
          curl -X POST https://pucktracker.onrender.com/api/v1/cron/update \
            -H "Authorization: Bearer ${{ secrets.PUCK_API_SECRET }}"